name: Build and Deploy GitHub Pages
on:
  push:
    branches:
      - "main"
jobs:
  build-and-deploy-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: npm install

      - name: Format
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Build GitHub Pages
        env:
          NODE_ENV: production
          PUBLIC_URL: https://stakefish.github.io/stanley-ipkiss/
        run: npm run build

      - name: Deploy GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Contributors
        uses: akhilmhdh/contributors-readme-action@v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
